# vim:ft=ansible:
---
- block:
  - name: Create the group
    group:
        name: narhs
        state: present
  - name: Create the user
    user:
        name: narhs
        comment: "Not a Real HMRC Service"
        groups: narhs
        system: yes
        #seuser: no
  - name: Clone the service
    git:
        repo: https://github.com/dwp-technology-design/not-a-real-hmrc-service.git
        dest: /opt/not-a-real-hmrc-service
  - name: Install dependencies
    command: make package
    args:
     chdir: /opt/not-a-real-hmrc-service
  - name: Change Ownership
    file:
        path: /opt/not-a-real-hmrc-service
        owner: narhs
        group: narhs
        recurse: yes
        state: directory
        #selevel:
        #setype: 
        #serole: 
  - name: Create logging folder
    file:
        path: /var/log/narhs
        owner: narhs
        group: narhs
        state: directory
        mode: "777"
  - name: Copy the systemd manifest
    copy: src=not-a-real-hmrc-service.service dest=/etc/systemd/system/not-a-real-hmrc-service.service 
  - name: Enable the Service
    command: systemctl enable not-a-real-hmrc-service.service
  become: yes
  become_method: sudo
