# vim:ft=ansible:
---
- name: Install EPEL Repository
  become: yes
  become_method: sudo
  yum:
    name: epel-release
    update_cache: yes
    state: installed
- name: Install Node.js
  become: yes
  become_method: sudo
  yum: 
    name: "{{ item }}"
    state: installed 
    update_cache: yes
  with_items:
  - nodejs
  - npm
  - git-all
